/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InvestmentType = IDL.Variant({
  'realEstate' : IDL.Null,
  'bond' : IDL.Null,
  'cash' : IDL.Null,
  'stock' : IDL.Null,
  'crypto' : IDL.Null,
});
export const Investment = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'type' : InvestmentType,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInvestmentRecord' : IDL.Func(
      [IDL.Text, IDL.Float64, InvestmentType],
      [Investment],
      [],
    ),
  'deleteInvestmentRecord' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listInvestmentRecords' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInvestmentRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, InvestmentType],
      [Investment],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InvestmentType = IDL.Variant({
    'realEstate' : IDL.Null,
    'bond' : IDL.Null,
    'cash' : IDL.Null,
    'stock' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const Investment = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'type' : InvestmentType,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInvestmentRecord' : IDL.Func(
        [IDL.Text, IDL.Float64, InvestmentType],
        [Investment],
        [],
      ),
    'deleteInvestmentRecord' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listInvestmentRecords' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInvestmentRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, InvestmentType],
        [Investment],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };